export const theme = {
    colors: {
        primary: '#4F46E5',
        secondary: '#F59E0B',
        success: '#22C55E',
        danger: '#f44336',
        warning: '#ff9800',
        info: '#4caf50',
        light: '#f8f9fa',
        dark: '#343a40',
        white: '#fff',
        black: '#000',
        gray: '#888',
        lightGray: '#e0e0e0',
        appBackground: '#F8FAFC',
        cardBackground: '#fff',
        priorityHigh: '#f44336',
        priorityMedium: '#ff9800',
        priorityLow: '#4caf50',
        textPrimary: '#333',
        textSecondary: '#555',
    },
    fontSizes: {
        extraLarge: '32px',
        large: '24px',
        medium: '13px',
        regular: '16px',
        small: '11px',
    },
    fontWeights: {
        light: 300,
        normal: 400,
        bold: 600,
    },
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    spacing: {
        xxs: '2px',
        xs: '4px',
        sm: '5px',
        ms: '8px',
        md: '10px',
        lg: '15px',
        xl: '20px',
        xxl: '30px',
    },
    borderRadius: {
        sm: '4px',
        md: '8px',
        lg: '14px',
        xl: '15px',
        xxl: '19px',
        xxxl: '24px',
        xxxxl: '30px',
        circle: '50%',
    },
    borderWidth: '1px',
    borderStyle: 'solid',
    boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)',
    boxShadowHover: '0 3px 7px rgba(0, 0, 0, 0.15)',
    transition: 'all 0.2s ease-in-out',
    columnWidth: '300px',
    hitZone: {
        small: '28px',
        medium: '30px',
        big: '35px'
    },
    app:{
        minHeight: '100vh',
        display: 'flex',
        flexDirection: 'column',
    },
    opacity: {
        disable: '0.55'
    }
};